@php($esEdicion = isset($hardware) && $hardware->exists)
<form method="POST" action="{{ $esEdicion ? route('hardware.update', $hardware->Hw_Serial) : route('hardware.store') }}" enctype="multipart/form-data" x-data="{ enviando: false }" @submit="enviando = true">
@csrf
@if($esEdicion) @method('PUT') @endif
<div class="mx-auto max-w-6xl space-y-5">
<header class="flex items-center gap-3"><span class="grid size-12 place-items-center rounded-2xl bg-brand-600 text-white"><i class="bi bi-pc-display text-xl"></i></span><div><h2 class="text-2xl font-extrabold text-slate-900">{{ $esEdicion ? 'Editar equipo' : 'Nuevo equipo' }}</h2><p class="text-sm text-slate-500">Completa la ficha en el orden del inventario.</p></div></header>
<section class="rounded-3xl border border-slate-200 bg-white shadow-card"><header class="border-b border-slate-100 px-6 py-4"><h3 class="font-bold text-slate-700"><i class="bi bi-person-vcard mr-2 text-brand-600"></i>1. Información del usuario</h3><p class="px-6 pb-3 text-xs text-slate-400">Escribe los datos del responsable. Se guardarán en el catálogo para reutilizarlos después.</p></header><div class="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-4"><label class="text-sm font-semibold text-slate-600">Código / documento *<input name="usuario_id" required maxlength="30" value="{{ old('usuario_id',$hardware->usuarioInv->UsuarioInvID ?? '') }}" placeholder="Ej: USU002" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-600">Nombre completo *<input name="usuario_nombre" required maxlength="50" value="{{ old('usuario_nombre',$hardware->usuarioInv->UsuarioInvNombre ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-600">Cargo<input name="usuario_cargo" maxlength="50" value="{{ old('usuario_cargo',$hardware->usuarioInv->UsuarioInvCargo ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-600">Área *<input name="usuario_area" required maxlength="50" value="{{ old('usuario_area',$hardware->usuarioInv->UsuarioInvArea ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-600 sm:col-span-2 lg:col-span-4">Correo electrónico *<input type="email" name="usuario_correo" required maxlength="50" value="{{ old('usuario_correo',$hardware->usuarioInv->UsuarioInvCorreo ?? '') }}" placeholder="usuario@empresa.com" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></label></div></section>
<section class="rounded-3xl border border-slate-200 bg-white shadow-card">
    <header class="border-b border-slate-100 px-6 py-4">
        <h3 class="font-bold text-slate-700"><i class="bi bi-card-text mr-2 text-brand-600"></i>2. Información general</h3>
    </header>
    <div class="grid gap-4 p-6 sm:grid-cols-2">
        <label class="text-sm font-semibold text-slate-600">
            Serial equipo *
            <input name="Hw_Serial" required maxlength="50" value="{{ old('Hw_Serial',$hardware->Hw_Serial ?? '') }}" @readonly($esEdicion) placeholder="Ej: IU89378" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono text-sm">
        </label>
        <label class="text-sm font-semibold text-slate-600">
            Serial de cargador
            <input name="Hw_Serial_Cargador" maxlength="50" value="{{ old('Hw_Serial_Cargador',$hardware->Hw_Serial_Cargador ?? '') }}" placeholder="Ej: CARG-098234" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono text-sm">
        </label>
        <label class="text-sm font-semibold text-slate-600">
            Nombre del equipo *
            <input name="Hw_Nombre" required maxlength="50" value="{{ old('Hw_Nombre',$hardware->Hw_Nombre ?? '') }}" placeholder="Ej: pow09w2w00" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">
        </label>
        <label class="text-sm font-semibold text-slate-600">
            Tipo de hardware *
            <select name="TipoID" required class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">
                <option value="">Seleccione...</option>
                @foreach($tipos as $t)
                    <option value="{{ $t->TipoID }}" @selected(old('TipoID',$hardware->TipoID ?? '') == $t->TipoID)>{{ $t->Nombre }}</option>
                @endforeach
            </select>
        </label>
        <label class="text-sm font-semibold text-slate-600 sm:col-span-2">
            Marca / modelo *
            <select name="ModeloID" required class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">
                <option value="">Seleccione...</option>
                @foreach($modelos as $m)
                    <option value="{{ $m->ModeloID }}" @selected(old('ModeloID',$hardware->ModeloID ?? '') == $m->ModeloID)>{{ $m->marca?->Nombre }} - {{ $m->Nombre }}</option>
                @endforeach
            </select>
        </label>
    </div>
</section>
<section class="rounded-3xl border border-slate-200 bg-white shadow-card"><header class="border-b border-slate-100 px-6 py-4"><h3 class="font-bold text-slate-700"><i class="bi bi-cpu mr-2 text-sky-600"></i>3. Características</h3></header><div class="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-3"><label class="text-sm font-semibold text-slate-600">Nombre del procesador *<input name="procesador_nombre" required maxlength="50" value="{{ old('procesador_nombre',$hardware->procesador->Nombre ?? '') }}" placeholder="Ej: Intel Core i5-12400" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-600">Velocidad<input name="procesador_velocidad" maxlength="10" value="{{ old('procesador_velocidad',$hardware->procesador->Velocidad ?? '') }}" placeholder="Ej: 2.50 GHz" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></label>@foreach([['Hw_Ram','RAM','Ej: 16 GB'],['Hw_Disco_Duro','Disco duro','Ej: SSD 512 GB'],['Hw_Estado','Estado','Ej: Bueno'],['MacEthernet','MAC Ethernet',''],['MacWireless','MAC Wireless','']] as [$name,$label,$placeholder])<label class="text-sm font-semibold text-slate-600">{{ $label }}<input name="{{ $name }}" value="{{ old($name,$hardware->$name ?? '') }}" maxlength="50" placeholder="{{ $placeholder }}" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-mono text-sm"></label>@endforeach</div></section>
<section class="rounded-3xl border border-slate-200 bg-white shadow-card"><header class="border-b border-slate-100 px-6 py-4"><h3 class="font-bold text-slate-700"><i class="bi bi-display mr-2 text-violet-600"></i>4. Monitor</h3></header><div class="p-6"><select name="MonitorID" class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Sin monitor</option>@foreach($monitores as $mo)<option value="{{ $mo->MonitorID }}" @selected(old('MonitorID',$hardware->MonitorID ?? '') == $mo->MonitorID)>{{ $mo->MonitorID }} - {{ $mo->Monitor_Modelo }}</option>@endforeach</select></div></section>
<section class="rounded-3xl border border-slate-200 bg-white shadow-card"><header class="border-b border-slate-100 px-6 py-4"><h3 class="font-bold text-slate-700"><i class="bi bi-mouse2 mr-2 text-amber-600"></i>5. Dispositivos</h3></header><div class="grid gap-3 p-6 sm:grid-cols-2 lg:grid-cols-4">@foreach($dispositivos as $d)<label class="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm text-slate-600"><input type="checkbox" name="dispositivos[]" value="{{ $d->Dispositivo_Codigo }}">{{ $d->Dispositivos_Nombre }}</label>@endforeach</div></section>
<section class="rounded-3xl border border-slate-200 bg-white shadow-card"><header class="border-b border-slate-100 px-6 py-4"><h3 class="font-bold text-slate-700"><i class="bi bi-chat-left-text mr-2 text-emerald-600"></i>6. Observaciones</h3></header><div class="p-6"><textarea name="observacion" maxlength="300" rows="3" placeholder="Observaciones iniciales..." class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"></textarea><input type="date" name="observacion_fecha" value="{{ now()->format('Y-m-d') }}" class="mt-3 rounded-xl border border-slate-200 px-3 py-2 text-sm"></div></section>
<section class="rounded-3xl border border-slate-200 bg-white shadow-card"><header class="border-b border-slate-100 px-6 py-4"><h3 class="font-bold text-slate-700"><i class="bi bi-window-stack mr-2 text-indigo-600"></i>7. Software <span class="text-xs font-normal text-slate-400">se asignará automáticamente</span></h3></header><div class="grid gap-5 p-6 lg:grid-cols-2"><div><p class="mb-2 text-xs font-bold uppercase text-slate-500">Licenciado</p>@foreach($softwareLicenciado as $sw)<label class="mb-2 flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm text-slate-600"><input type="checkbox" name="software_licenciado[]" value="{{ $sw->Software_Id }}"><span class="min-w-0 flex-1">{{ $sw->Software_Nombre ?: 'Licencia #' . $sw->Software_Id }}<small class="block text-xs text-slate-400">{{ $sw->Software_Clave ?: 'Sin clave' }}</small></span><span class="text-xs text-slate-400">{{ $sw->Software_Cantidad ?? 'Ilimitado' }}</span></label>@endforeach</div><div><p class="mb-2 text-xs font-bold uppercase text-slate-500">No licenciado</p>@foreach($softwareNoLicenciado as $sw)<label class="mb-2 flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm text-slate-600"><input type="checkbox" name="software_no_licenciado[]" value="{{ $sw->Softwarenl_Id }}">{{ $sw->Softwarenl_Nombre }} <span class="ml-auto text-xs text-slate-400">{{ $sw->Softwarenl_Version }}</span></label>@endforeach</div></div></section>
<div class="sticky bottom-4 flex justify-between rounded-2xl border border-slate-200 bg-white/90 p-3 shadow-pop"><a href="{{ route('hardware.index') }}" class="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500">Cancelar</a><button :disabled="enviando" class="rounded-xl bg-brand-600 px-6 py-2.5 text-sm font-bold text-white"><i class="bi bi-save mr-2"></i><span x-show="!enviando">{{ $esEdicion ? 'Guardar cambios' : 'Crear equipo' }}</span><span x-show="enviando" x-cloak>Guardando...</span></button></div>
</div></form>
